language: python

notifications:
  email: false

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libhdf5-serial-dev
    - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install unittest2; fi
    - pip install numpy
    - pip install --install-option="--no-cython-compile" cython

install: 
    - python setup.py build -f

script: "python setup.py test"
