language: python

notifications:
  email: false

addons:
  apt:
    packages:
      - libhdf5-serial-dev

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

env:
  - TOXENV=py26-test-deps
  - TOXENV=py27-test-deps
  - TOXENV=py33-test-deps
  - TOXENV=py34-test-deps

install:
  - pip install tox

script:
  - tox
