steps:
- download: current
  artifact: ${{ parameters.platform }}_wheels
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'
- script: |
    python -m pip install --upgrade pip
    pip install tox codecov
  displayName: Install tox
- script: |
    ls $PIPELINE_WORKSPACE/${{ parameters.platform }}_wheels/
    tox --installpkg $PIPELINE_WORKSPACE/${{ parameters.platform }}_wheels/$WHL_FILE
