steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip
    pip install cibuildwheel==1.6.0
  displayName: 'Install cibuildwheel'

- script: env
  displayName: 'print env'

- script: |
    cibuildwheel --print-build-identifiers
    cibuildwheel --output-dir wheelhouse .
- task: PublishPipelineArtifacts@1
  inputs:
    pathtoPublish: 'wheelhouse'
    artifact: manylinux_wheels
